Optional feature-filter for decorateLayer
mapbox/tile-decorator pull request #5
Opened 2016-12-14 18:50 UTC by rodowi

Closes #2 

This PR adds a parameter for dropping features during tile decoration.

Notes:
- This PR carries a commit from #4 to make tests pass. We can remove this before merging.
- Might be useful to move the `getAttribute` helper to Decorator, so we can filter features out of the box.

cc: @aaronlidman @mourner

2016-12-14 19:32 UTC, rodowi commented
per slack @aaronlidman 
we should pass an array of requiredProps instead so we can serialize params passed to tilelive-decorator

2016-12-14 21:02 UTC, rodowi commented
As suggested in #2, I replaced the filter function with a requiredKeys array.

Features missing any of those keys will be skipped.

2016-12-15 05:10 UTC, rodowi commented
hey @mourner, when you get a minute would you mind taking a look at the suggested implementation?

Basically we are adding a 4th parameter to decorateLayer, so we can pass an array of required keys per feature and skip geometries that are missing any of these.

```js
var keysToKeep = ['id', 'type', 'color', 'foo'];
var required = ['foo'];
Decorator.decorateLayer(layer, keysToKeep, null, required);
```

2016-12-15 15:21 UTC, mourner requested changes

2016-12-15 15:21 UTC, mourner commented on index.js
> +        }
`splice` is very expensive. Can we avoid it? `layer.features = layer.features.filter(...)` would probably be much faster.

2016-12-15 15:21 UTC, mourner commented on index.js
> +    }
`indexOf` when doing `hasAllKeys` check can be expensive if we have many keys. Can we do it in the same manner as the `keepLookup` logic above — building a hashmap of required indices, and then checking against it instantly?

2016-12-15 15:21 UTC, mourner commented on index.js
> +}
With a hashmap (as suggested above), knowing that tag keys are unique in a feature, we can do it faster like this:

```js
var numKeys = 0;
for (var i = 0; i < tagKeys.length; i += 2) {
    if (requiredLookup[tagKeys[i]]) numKeys++;
}
return numKeys === numRequiredKeys;
```

2016-12-15 15:23 UTC, rodowi commented
Branch rebased to pull test fixes #6 and to squash filterFunc old commits

2016-12-15 15:28 UTC, mourner commented
Also, let's avoid version bump commits in a PR. Those are best added with `npm version` command on a clean master branch after the decision to release.

2016-12-15 15:32 UTC, rodowi commented
Gotcha. Removed version bump.

2016-12-15 16:45 UTC, rodowi commented on index.js
> +    }
sure, makes sense
will also take a look at the bench script to confirm that we don't add too much computation

2016-12-15 16:54 UTC, rodowi commented on index.js
> +    }
benchtest for decorate went from 32ms to 20ms after updating hasAllKeys to use a hashmap (ed80768) 👍

2016-12-15 16:57 UTC, rodowi commented
Seeing a perf improvement after replacing indexOf with a hashmap lookup for hasAllKeys (ed80768)

```
➜  tile-decorator git:(feature-filter) node bench/bench.js
read tile: 27ms
get keys: 4ms
decorate: 20ms
merge: 29ms
write tile: 19ms
total: 103ms
merged 10031 features into 428
size went from 430088 to 89053
➜  tile-decorator git:(feature-filter) gcb feature-filter-before
Switched to a new branch 'feature-filter-before'
➜  tile-decorator git:(feature-filter-before) git reset HEAD~1
Unstaged changes after reset:
M	index.js
➜  tile-decorator git:(feature-filter-before) ✗ git checkout -- .
➜  tile-decorator git:(feature-filter-before) node bench/bench.js
read tile: 26ms
get keys: 2ms
decorate: 32ms
merge: 29ms
write tile: 19ms
total: 112ms
merged 10031 features into 428
size went from 430088 to 89053
```

2016-12-15 16:59 UTC, rodowi commented on index.js
> +}
Just read this msg after implementing the lookup fix :|
Passing a static integer for numRequiredKeys should improve my last commit. Will add this. Thanks!

2016-12-15 17:31 UTC, rodowi commented
@mourner I've added all your suggestions. If it works I'll squash the implementation into one commit.

```
node bench/bench.js
read tile: 25ms
get keys: 3ms
decorate: 16ms <------ splice was expensive indeed
merge: 32ms
write tile: 16ms
total: 96ms
merged 10031 features into 428
size went from 430088 to 89053
```

2016-12-15 18:06 UTC, mourner approved these changes
Looks great! I think this is ready to ship. Just a few minor remarks.

2016-12-15 18:06 UTC, mourner commented on index.js
> +    for (var i = 0, j = tags.length; i < j; i += 2) {
You don't have to cache the length in for loops in modern JS engines. This is optimized automatically.

2016-12-15 18:06 UTC, mourner commented on index.js
> +        layer.features = features;
You can just do `layer.features = layer.features.filter(...)` since `features` array is not used after that.

2016-12-15 18:22 UTC, rodowi commented
Code updated 👍 @mourner 
I'm rebasing now...

2016-12-15 19:51 UTC, merged